name: interview-analysis-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pandas
  - scikit-learn=1.1.3
  - opencv
  - nltk
  - flask
  - pip
  - pip:
      - tensorflow==2.13.0
      - keras==2.13.1
      - moviepy==1.0.3
      - pydub
      - assemblyai
      - fer
      - facenet-pytorch
      - praat-parselmouth
      - torch
      - torchvision
      - matplotlib
      - pillow
      - python-dotenv
