name: posture-analysis-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - flask
  - opencv
  - pip
  - pip:
      - "numpy<2"
      - mediapipe
      - protobuf==3.20.3
      - python-dotenv
